name: Compilar Instalador

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Inno Setup
        run: choco install innosetup -y

      - name: Compilar Script
        run: |
          "C:\Users\gneves1\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Inno Setup 6\ISCC.exe" ExtratorDataSul_Setup.iss

      - name: Upload do Instalador
        uses: actions/upload-artifact@v4
        with:
          name: ExtratorDataSul
          path: Output/ExtratorDataSul.exe
